create table KPIS(
KPI_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
NAME           Varchar2(100 BYTE) Not Null,
STATUS	       VARCHAR2(1)        DEFAULT '0',
CREATED	       DATE	          Not Null,
CREATED_BY     VARCHAR2(255 BYTE)	  Not Null,
UPDATED	       DATE               Not Null,
UPDATED_BY     VARCHAR2(255 BYTE)	  Not Null);

CREATE or REPLACE TRIGGER KPIS_TRIGGER
before UPDATE OR INSERT ON KPIS
FOR EACH ROW
DECLARE
BEGIN
    if inserting then 
        :new.created := sysdate; 
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.updated := sysdate; 
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user); 
end;

create table HR_BONUS_VARIABLES(
HR_BONUS_VARIABLES_ID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
KPI_ID                   NUMBER Not Null,
CHAIN_ID                NUMBER NOT NULL,
PERCENTAJE              Number             Default 0 Not Null,
FROM_MINIMUM            Number             Default 0 Not Null,
UPTO_MAXIMUM            Number             Default 0 Not Null,
CREATED	                DATE	          Not Null,
CREATED_BY              VARCHAR2(255 BYTE)	  Not Null,
UPDATED	                DATE               Not Null,
UPDATED_BY              VARCHAR2(255 BYTE)	  Not Null);

alter table
   HR_BONUS_VARIABLES
add constraint
   FK_HR_BONUS_VARIABLES_KPIS FOREIGN KEY (KPI_ID)
references
   KPIS (KPI_ID)
initially deferred deferrable;
/

alter table
   HR_BONUS_VARIABLES
add constraint
   FK_HR_BONUS_VARIABLES_CHAINS FOREIGN KEY (CHAIN_ID)
references
   CHAINS (CHAIN_ID)
initially deferred deferrable;
/

CREATE or REPLACE TRIGGER HR_BONUS_VARIABLES_TRIGGER
before UPDATE OR INSERT ON HR_BONUS_VARIABLES
FOR EACH ROW
DECLARE
BEGIN
    if inserting then 
        :new.created := sysdate; 
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.updated := sysdate; 
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user); 
end;



github
gitflow

winget install --id Git.Git -e --source winget
github.com
proyecto_3@unicomer.com
pass:Marzo2022*
user:proyecto-3-unicomer

git init
git config user.name "proyecto-3-unicomer"
git config user.email "proyecto_3@unicomer.com"


git init
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/proyecto-3-unicomer/proyecto-3-unicomer.git
git push -u origin main


error: remote origin already exists
git remote remove origin
